---
- name: Start pega tomcat application server
  hosts: pega_tomcat_server
  connection: ssh
  remote_user: root
  gather_facts: true
  become: yes
  become_method: sudo
  
  roles:
   - tomcat_start
   
        